sudo: required
services:
 - docker

before_install:
 - docker build -t akashmaggon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akashmaggon/docker-react npm run test

deploy: 
 provider:elasticbeanstalk 
 region: "ap-south-1"
 app:"Docker React"
 env:"DockerReact-env"
 bucket_name: "elasticbeanstalk-ap-south-1-329640325154"
 bucket_path: "Docker React"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
